version: '3'
services:
  spark-master:
    image: dfunto/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: dfunto/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-notebook:
    image: dfunto/spark-notebook:3.1.1-hadoop3.2
    container_name: spark-notebook
    ports:
      - "8888:8888"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

# Spark not usable yet, please view build.sh script
#  spark-livy:
#    image: dfunto/spark-livy:2.4.7-hadoop2.7
#    container_name: spark-livy
#    ports:
#      - "8998:8998"
#    environment:
#      - "SPARK_MASTER=spark://spark-master:7077"


